version: '3.8'

services:
  app:
    build: . 
   # command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    container_name: django-intro
    volumes:
      - .:/app
    ports: 
      - 8000:8000

networks:
  default:
    name: development
    external: true
      


  
    
   