# Generated by Django 4.1.4 on 2022-12-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='people',
        ),
    ]
