# Generated by Django 4.1.4 on 2022-12-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
