# Generated by Django 4.1.4 on 2022-12-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_person_gender_alter_person_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
