# Generated by Django 4.1.4 on 2022-12-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_phone_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_two',
            field=models.CharField(default='', max_length=200),
        ),
    ]
