# Generated by Django 4.1.4 on 2022-12-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_person_address_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
    ]
