# Generated by Django 4.1.4 on 2022-12-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_person_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.person',),
        ),
    ]
